// export const log = (Symbol('Log') as unknown) as 'Log';
// export const success = (Symbol('Success') as unknown) as 'Success';
// export const warn = (Symbol('Warn') as unknown) as 'Warn';
// export const error = (Symbol('Error') as unknown) as 'Error';
// export const heart = (Symbol('Heart') as unknown) as 'Heart';
// export const help = (Symbol('Help') as unknown) as 'Help';
// export const message = (Symbol('Message') as unknown) as 'Message';
// export const refresh = (Symbol('Refresh') as unknown) as 'Refresh';
// export const setting = (Symbol('Setting') as unknown) as 'Setting';
// export const remove = (Symbol('Remove') as unknown) as 'Remove';
// export const star = (Symbol('Star') as unknown) as 'Star';
// export const upload = (Symbol('Upload') as unknown) as 'Upload';
// export const user = (Symbol('User') as unknown) as 'User';
// export const play = (Symbol('Play') as unknown) as 'Play';
// export const mail = (Symbol('Mail') as unknown) as 'Mail';
// export const link = (Symbol('Link') as unknown) as 'Link';
// export const bookmark = (Symbol('Bookmark') as unknown) as 'Bookmark';

import log from './log';
export {log};
